[profile.default]
solc_version = "0.8.19"
eth_rpc_url = "https://rpc.ankr.com/eth_sepolia"

fs_permissions = [
  { access = "read-write", path = "./addresses.json" },
  { access = "read-write", path = "./out" },
]

[rpc_endpoints]
gnosis = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
gnosis2 = "https://rpc.ankr.com/gnosis"

sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
sepolia2 = "https://rpc.ankr.com/eth_sepolia"

local = "http://127.0.0.1:8545"

[etherscan]
gnosis = { key = "${ETHERSCAN_API_KEY_GNOSIS}" }

sepolia = { key = "${ETHERSCAN_API_KEY}" }
