[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.19"

fs_permissions = [
  { access = "read-write", path = "./addresses.json" },
  { access = "read-write", path = "./out" },
]

[profile.sepolia]
eth_rpc_url = "sepolia"
fork_block_number = 4342233

[profile.gnosis]
eth_rpc_url = "gnosis"
fork_block_number = 30066829

[profile.anvil]
eth_rpc_url = "anvil"

[profile.incentives]
src = 'lib/storage-incentives'
test = 'lib/storage-incentives/test'
script = 'lib/storage-incentives/script'
lib = ['lib/storage-incentives/lib']
solc_version = '0.8.1'


[rpc_endpoints]
gnosis1 = "https://rpc.gnosischain.com"
gnosis = "https://rpc.ankr.com/gnosis"

sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
sepolia2 = "https://rpc.ankr.com/eth_sepolia"

anvil = "http://127.0.0.1:8545"

[etherscan]
gnosis = { key = "${ETHERSCAN_API_KEY_GNOSIS}" }

sepolia = { key = "${ETHERSCAN_API_KEY}" }
